CREATE TABLE PUBLIC.USERS (
  ID   INT PRIMARY KEY NOT NULL,
  NAME VARCHAR2(256) NOT NULL
);

CREATE TABLE PUBLIC.ALIASES (
  ID   INT PRIMARY KEY NOT NULL,
  UID  INT NOT NULL,
  NAME VARCHAR2(256) NOT NULL
);